version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6000:3000
    environment:
      - NODE_ENV=production
    networks:
      - network
    container_name: leak-chker
networks:
  network:
    driver: bridge
